Coupon
Gromiko-Evgeniy/ModsenOnlineStore pull request #8
Opened 2023-06-17 01:33 UTC by Mary0110

2023-06-19 07:49 UTC, elv1sabene requested changes

2023-06-19 07:49 UTC, elv1sabene commented on ModsenOnlineStore.Store.API/Controllers/CouponsController.cs
> +            if (couponInfo.Success is false)
you can write just `if (!couponInfo.Success)`

2023-06-19 07:49 UTC, elv1sabene commented on ModsenOnlineStore.Store.Domain/DTOs/CouponDTO/ApplyCouponDTO.cs
> +    public int orderId { get; set; }
use PascalCase

2023-06-19 07:49 UTC, elv1sabene commented on ModsenOnlineStore.Store.Infrastructure/Data/CouponRepository.cs
> +    public async Task<Order?> ApplyCoupon(int couponId, int orderId)
Why is this method in the repository?
repositories are used for data storage access only, all business rules should be in application layer, e.g. services

2023-06-19 07:49 UTC, elv1sabene commented on ModsenOnlineStore.Store.API/Controllers/CouponsController.cs
> +            return Ok(await couponService.ApplyCoupon(data));
Is it really always Ok regardless ApplyCoupon operation result?

2023-06-19 12:22 UTC, Mary0110 commented on ModsenOnlineStore.Store.API/Controllers/CouponsController.cs
> +            if (couponInfo.Success is false)
fixed

2023-06-19 12:22 UTC, Mary0110 commented on ModsenOnlineStore.Store.Domain/DTOs/CouponDTO/ApplyCouponDTO.cs
> +    public int orderId { get; set; }
fixed

2023-06-19 12:23 UTC, Mary0110 commented on ModsenOnlineStore.Store.Infrastructure/Data/CouponRepository.cs
> +    public async Task<Order?> ApplyCoupon(int couponId, int orderId)
fixed

2023-06-19 12:23 UTC, Mary0110 commented on ModsenOnlineStore.Store.API/Controllers/CouponsController.cs
> +            return Ok(await couponService.ApplyCoupon(data));
fixed

2023-06-20 07:31 UTC, elv1sabene approved these changes

2023-06-20 07:31 UTC, elv1sabene commented on ModsenOnlineStore.Store.Infrastructure/Data/DbInitializer.cs
> +        };
do you need these braces?

2023-06-20 07:31 UTC, elv1sabene commented on ModsenOnlineStore.Store.Infrastructure/Data/DbInitializer.cs
> +        };
same

2023-06-20 07:31 UTC, elv1sabene commented on ModsenOnlineStore.Store.Infrastructure/Data/DbInitializer.cs
> +            context.Coupons.AddRange(new Domain.Entities.Coupon[] { firstc, secondc });
why is there an indentation here?

2023-06-20 07:31 UTC, elv1sabene commented on ModsenOnlineStore.Store.Infrastructure/Data/DbInitializer.cs
> +        // if (!context.Coupons.Any()) {
do you need this?

2023-06-20 10:50 UTC, merged